Next.jsで作ったデモをGithub Pagesに置く
open-geocoding/open-reverse-geocoder pull request #29
Opened 2021-12-01 09:24 UTC by yuiseki

## What do this pull request

- Next.jsでこのnpm packageを使うデモプロジェクトをGithub Pagesにデプロイします

## Why do this pull request

- Reactでどのように使うのかの実例があったほうが良いと考えた
- `create-react-app` は相性問題などがあり厄介なので、一番手軽かつ柔軟にReactのSPAを構築できるNext.jsを使った
- 地図には、 `react-map-gl` と `maplibre-gl` を採用した
- https://yuiseki.github.io/open-reverse-geocoder/ でDeployに成功しており、動作確認が可能

## Impact range for user

- Nothing.

2021-12-01 13:15 UTC, silloi commented
> create-react-app は相性問題などがあり厄介なので

[IMO] 純粋な SPA として構築するなら、今だと vite を使って立ち上げるのが一番手っ取り早そうです。
（こちらも Native ESM でないパッケージを import しようとするとハマったりするのですが）
https://vitejs.dev/guide/
もちろん、多くの場合は SSR や SSG で構築することになると思うので、デモ自体は Next.js でいいと思います！

2021-12-02 15:08 UTC, JinIgarashi requested changes
デモサイト良いですね。何点かコメントしました。

2021-12-02 15:08 UTC, JinIgarashi commented on .github/workflows/publish_gh_pages.yml
> +      - master
https://github.com/open-geocoding/open-reverse-geocoder/pull/28のPRで行ったCIを利用するように修正いただけたら良いかと思います。
BuildとLintまで成功したらデプロイするイメージ

2021-12-02 15:08 UTC, JinIgarashi commented on demo/package.json
> +  "private": true,
`private: false`に修正お願いします。

2021-12-02 15:08 UTC, JinIgarashi commented on demo/pages/index.tsx
> +  const [address, setAddress] = useState('地図を動かしてください')
日本以外にも対応していきたいので、英語でも表示できるといいと思います。

2021-12-02 15:08 UTC, JinIgarashi commented on demo/pages/index.tsx
> +    setAddress(result.prefecture + result.city)
これだと日本の住所以外だとNaNになってしまうので、今対応しているルワンダとDRC、あと今後追加していきたい他国でもちゃんと表示できるようにしたいです。

2021-12-02 15:08 UTC, JinIgarashi commented on demo/pages/index.tsx
> +          mapStyle="https://raw.githubusercontent.com/geolonia/notebook/master/style.json"
geoloniaの背景地図だと日本以外はうまく表示できないので、他のものに変えたいですね。
何かいいのがあるかな。

2021-12-02 20:24 UTC, JinIgarashi commented on demo/pages/index.tsx
> +          mapStyle="https://raw.githubusercontent.com/geolonia/notebook/master/style.json"
https://raw.githubusercontent.com/watergis/ne2geojson/gh-pages/style.json

自分の水道マップの低縮尺用に作ったNatural earthのスタイルがあるんですが、これ使えないかな。高縮尺見れないですが…

2022-02-13 09:12 UTC, yuiseki commented
Mapbox style specificationについての理解が浅かったのと、Vite+Reactで作り直すべきだと考え直したので、このPull requestは閉じます。反応が遅れてすみません。

2022-02-13 09:12 UTC, closed without merging